### ISSUE TITLE
installing / running on 32bit linux? (CentOS)

### ISSUE THREAD

**Issue by tunnckoCore** [moose-team/friends#110]
when i try to follow the readme it errors as ever node-gyp.. damn, i hate it.

when run just `npm i -d`
```js
> leveldown@1.0.2 install /home/charlike/dev/friends/node_modules/leveldown
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@1.5.1 | linux | ia32
child_process: customFds option is deprecated, use stdio instead.
gyp info spawn python
gyp info spawn args [ '/home/charlike/.nvm/versions/io.js/v1.5.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/charlike/dev/friends/node_modules/leveldown/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/charlike/.nvm/versions/io.js/v1.5.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/charlike/.node-gyp/1.5.1/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/charlike/.node-gyp/1.5.1',
gyp info spawn args   '-Dmodule_root_dir=/home/charlike/dev/friends/node_modules/leveldown',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/charlike/dev/friends/node_modules/leveldown/build'
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/builder.o
make: g++: Command not found
make: *** [Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/builder.o] Error 127
make: Leaving directory `/home/charlike/dev/friends/node_modules/leveldown/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/charlike/.nvm/versions/io.js/v1.5.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1044:12)
gyp ERR! System Linux 2.6.32-504.12.2.el6.i686
gyp ERR! command "node" "/home/charlike/.nvm/versions/io.js/v1.5.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/charlike/dev/friends/node_modules/leveldown
gyp ERR! node -v v1.5.1
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm info postinstall electron-prebuilt@0.25.1
npm info leveldown@1.0.2 Failed to exec install script
npm ERR! Linux 2.6.32-504.12.2.el6.i686
npm ERR! argv "/home/charlike/.nvm/versions/io.js/v1.5.1/bin/iojs" "/home/charlike/.nvm/versions/io.js/v1.5.1/bin/npm" "i" "-d"
npm ERR! node v1.5.1
npm ERR! npm  v2.7.0

npm ERR! shasum check failed for /tmp/npm-12417-28cad8f9/registry.npmjs.org/byline/-/byline-4.2.1.tgz
npm ERR! Expected: f74a66fa6d8feff88b2725e0b2b0cf830cdf3f86
npm ERR! Actual:   159a948ac927b6549a1105e50e4d614ab3a0b33a
npm ERR! From:     https://registry.npmjs.org/byline/-/byline-4.2.1.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm info preuninstall silence-chromium@2.0.0
npm info uninstall silence-chromium@2.0.0
npm info postuninstall silence-chromium@2.0.0
npm info preuninstall rich-message@1.0.0
npm info uninstall rich-message@1.0.0
npm info postuninstall rich-message@1.0.0
npm info preuninstall leveldown@1.0.2
npm info uninstall leveldown@1.0.2
npm info postuninstall leveldown@1.0.2

npm ERR! Please include the following file with any support request:
npm ERR!     /home/charlike/dev/friends/npm-debug.log
```

i can share npm-debug.log if you want, it is 51k lines :lollipop:

**Comment by beaugunderson** [comment]
it did work for me but required iojs 1.8.1 and npm 2.8.4

**Comment by ngoldman** [comment]
@tunnckoCore can you try upgrading to latest iojs? looks like you're running v1.5.1, we're recommending v1.8.1. That might not fix it but hopefully it will :smile_cat:

**Comment by tunnckoCore** [comment]
ohh, yea sure, im sleepy. will try and report

**Comment by tunnckoCore** [comment]
@ngoldman mnope, not work.

```
[charlike@dev friends]$ node -v
v1.8.1
[charlike@dev friends]$ npm -v
2.9.0
```

**Comment by KenanY** [comment]
```
make: g++: Command not found
```

`g++` not installed? (or not in `PATH`?). I believe you can set the `CXX` environment variable if you want to use a different compiler.

```
npm ERR! shasum check failed for /tmp/npm-12417-28cad8f9/registry.npmjs.org/byline/-/byline-4.2.1.tgz
npm ERR! Expected: f74a66fa6d8feff88b2725e0b2b0cf830cdf3f86
npm ERR! Actual:   159a948ac927b6549a1105e50e4d614ab3a0b33a
npm ERR! From:     https://registry.npmjs.org/byline/-/byline-4.2.1.tgz
```

`npm cache clean byline` is usually enough to fix this.

**Comment by tunnckoCore** [comment]
> g++ not installed?

yep, good point, thanks.

But again fails, this time electron-prebuilt, cuz (i guess) cant find install.js
```
npm info linkStuff rich-message@1.0.1
npm info install rich-message@1.0.1
npm info postinstall rich-message@1.0.1
npm info postinstall leveldown@1.0.2
npm ERR! Linux 2.6.32-504.12.2.el6.i686
npm ERR! argv "/home/charlike/.nvm/versions/io.js/v1.8.1/bin/iojs" "/home/charlike/.nvm/versions/io.js/v1.8.1/bin/npm" "i" "-d"
npm ERR! node v1.8.1
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.25.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-prebuilt@0.25.2 install script 'node install.js'.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.
npm info preuninstall electron-prebuilt@0.25.2
npm info uninstall electron-prebuilt@0.25.2
npm info postuninstall electron-prebuilt@0.25.2

npm ERR! Please include the following file with any support request:
npm ERR!     /home/charlike/dev/friends/npm-debug.log

```

**Comment by tunnckoCore** [comment]
Okey again.

```
[charlike@home friends]$ node -v
v2.0.0
[charlike@home friends]$ npm -v
2.9.0
```
problem is that electron-prebuilt trying to run `node install.js` but that file isn't in the repo.

**Comment by bcomnes** [comment]
Try running it a second time: see https://github.com/mafintosh/electron-prebuilt/issues/20

**Comment by tunnckoCore** [comment]
haha, cool, very thanks! It seems it start doing and downloading something, lol. Will report back. :)

**Comment by tunnckoCore** [comment]
dohhh... that node-gyp... fails. it is installed globally.

```
...

  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/hash.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/logging.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/options.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/status.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/port/port_posix.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/env_posix.o
  AR(target) Release/obj.target/deps/leveldb/leveldb.a
  COPY Release/leveldb.a
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy.o
  AR(target) Release/obj.target/deps/snappy/snappy.a
  COPY Release/snappy.a
  CXX(target) Release/obj.target/leveldown/src/batch.o
In file included from ../src/batch.cc:1:
/home/charlike/.node-gyp/2.0.0/src/node.h:80: error: wrong number of arguments specified for ‘deprecated’ attribute
In file included from ../src/batch.cc:1:
/home/charlike/.node-gyp/2.0.0/src/node.h:252: error: wrong number of arguments specified for ‘deprecated’ attribute
/home/charlike/.node-gyp/2.0.0/src/node.h:262: error: wrong number of arguments specified for ‘deprecated’ attribute
/home/charlike/.node-gyp/2.0.0/src/node.h:278: error: wrong number of arguments specified for ‘deprecated’ attribute
/home/charlike/.node-gyp/2.0.0/src/node.h:297: error: wrong number of arguments specified for ‘deprecated’ attribute
/home/charlike/.node-gyp/2.0.0/src/node.h:310: error: wrong number of arguments specified for ‘deprecated’ attribute
In file included from /home/charlike/.node-gyp/2.0.0/src/node_buffer.h:5,
                 from ../src/batch.cc:2:
/home/charlike/.node-gyp/2.0.0/src/smalloc.h:29: error: wrong number of arguments specified for ‘deprecated’ attribute
/home/charlike/.node-gyp/2.0.0/src/smalloc.h:60: error: wrong number of arguments specified for ‘deprecated’ attribute
/home/charlike/.node-gyp/2.0.0/src/smalloc.h:67: error: wrong number of arguments specified for ‘deprecated’ attribute
/home/charlike/.node-gyp/2.0.0/src/smalloc.h:75: error: wrong number of arguments specified for ‘deprecated’ attribute
/home/charlike/.node-gyp/2.0.0/src/smalloc.h:84: error: wrong number of arguments specified for ‘deprecated’ attribute
/home/charlike/.node-gyp/2.0.0/src/smalloc.h:99: error: wrong number of arguments specified for ‘deprecated’ attribute
/home/charlike/.node-gyp/2.0.0/src/smalloc.h:108: error: wrong number of arguments specified for ‘deprecated’ attribute
In file included from ../src/batch.cc:2:
/home/charlike/.node-gyp/2.0.0/src/node_buffer.h:26: error: wrong number of arguments specified for ‘deprecated’ attribute
/home/charlike/.node-gyp/2.0.0/src/node_buffer.h:34: error: wrong number of arguments specified for ‘deprecated’ attribute
/home/charlike/.node-gyp/2.0.0/src/node_buffer.h:44: error: wrong number of arguments specified for ‘deprecated’ attribute
/home/charlike/.node-gyp/2.0.0/src/node_buffer.h:54: error: wrong number of arguments specified for ‘deprecated’ attribute
/home/charlike/.node-gyp/2.0.0/src/node_buffer.h:67: error: wrong number of arguments specified for ‘deprecated’ attribute
make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
make: Leaving directory `/home/charlike/dev/friends/node_modules/leveldown/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/charlike/.nvm/versions/io.js/v2.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
gyp ERR! System Linux 2.6.32-504.12.2.el6.i686
gyp ERR! command "/home/charlike/.nvm/versions/io.js/v2.0.0/bin/iojs" "/home/charlike/.nvm/versions/io.js/v2.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/charlike/dev/friends/node_modules/leveldown
gyp ERR! node -v v2.0.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm info leveldown@1.0.2 Failed to exec install script
npm ERR! Linux 2.6.32-504.12.2.el6.i686
npm ERR! argv "/home/charlike/.nvm/versions/io.js/v2.0.0/bin/iojs" "/home/charlike/.nvm/versions/io.js/v2.0.0/bin/npm" "i" "-d"
npm ERR! node v2.0.0
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE

npm ERR! leveldown@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@1.0.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.
npm info preuninstall leveldown@1.0.2
npm info uninstall leveldown@1.0.2
npm info postuninstall leveldown@1.0.2

npm ERR! Please include the following file with any support request:
npm ERR!     /home/charlike/dev/friends/npm-debug.log
```

**Comment by mafintosh** [comment]
I'm not sure iojs 2.0.0 is supported yet. I've had some leveldown
compilation errors myself today when using it. Clearing your node_modules
folder and reinstalling deps might fix it though
