### ISSUE TITLE
[Installation] I get this error while installation

### ISSUE THREAD

**Issue by mihir-harbinger** [moose-team/friends#159]
```
mihir@SCS-L53:~/friends$ npm install
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
extract -> gunzTarPerm    / |###################################################extract -> gunzTarPerm    / |###################################################extract -> gunzTarPerm    \ |###################################################extract -> gunzTarPerm    \ |###################################################extract -> gunzTarPerm    \ |###################################################
> leveldown@1.4.4 install /home/mihir/friends/node_modules/leveldown
> prebuild --install

module.js:341
    throw err;
    ^

Error: Cannot find module 'inherits'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/mihir/friends/node_modules/hyperquest/node_modules/readable-stream/lib/_stream_duplex.js:40:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

```

**Comment by mihir-harbinger** [comment]
Fixed itself after running `npm install` once again.
