### ISSUE TITLE
no such file electron-prebuilt/path.txt

### ISSUE THREAD

**Issue by goodmanlu** [moose-team/friends#169]
~/friends$ npm start

> friends@1.0.0 start /home/luqingzhi/friends
> npm run build-css && electron index.js 2>&1 | silence-chromium

> friends@1.0.0 build-css /home/luqingzhi/friends
> stylus -u nib app/style/index.styl -o app/style/bundle.css -c

  compiled app/style/bundle.css
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open '/home/luqingzhi/friends/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (/home/luqingzhi/friends/node_modules/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

**Comment by akashnimare** [comment]
@goodmanlu Here - https://github.com/electron-userland/electron-prebuilt/issues/76

**Comment by ungoldman** [comment]
This looks to be an electron-prebuilt issue, hope you solved it!
